# Generated by Django 3.0.5 on 2023-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='owned_teachers',
        ),
        migrations.AddField(
            model_name='studentextra',
            name='owned_teachers',
            field=models.ManyToManyField(to='center.TeacherExtra'),
        ),
    ]
